export const GRAPH = {
    width: 2400,
    height: 800,
    nodeWidth: 140,
    nodeHeight: 150,
    lanes: 3,
    gapX: 185,
    startX: 120,
    startY: 80,
    laneGap: 120,
};

export const state = {
    scale: 1,
    offsetX: 30,
    offsetY: 30,
    idealOffsetX: 0,
    idealOffsetY: 0,
    isDraggingViewport: false,
    dragMoved: false,
    dragStartClientX: 0,
    dragStartClientY: 0,
    startOffsetX: 0,
    startOffsetY: 0,
    suppressClickUntil: 0,
    allClusters: [],
    filteredClusters: [],
    searchQuery: '',
    faceFilter: null,
    groupBy: 'date',
    semanticMatches: [],
    inDetailsView: false,
    fullClusterPositions: [],
    lastPositions: [],
    clusterElements: new Map(),
    virtualizedGraphActive: false,
    renderedClusterRange: null,
    draggedNodeId: null,
    nodeDragMoved: false,
    map: null,
    mapTileLayer: null,
    mapMarkers: [],
    mapLockedLat: null,
    showMap: false,
    currentMapStyle: 'voyager',
    mapSearchLocked: false,
    people: [],
    peopleViewActive: false,
    personFilter: null,
    peopleSortBy: 'photos',
    libraryDirty: false,
    navigationToken: 0,
    treeData: null,
    treeViewActive: false,
    linkingPerson: null,
    highlightedPath: [],
    openedFromMap: false,
    openedFromPeople: false,
    openedFromTree: false,
    mapFitting: false,
    indexingComplete: {
        visual: false,
        faces: false,
        vectors: false,
    },
    clusterDataModeByGroup: {},
    clusterPageStateByGroup: {},
};

export const ui = {
    viewport: document.getElementById('viewport'),
    gallery: document.getElementById('gallery'),
    connections: document.getElementById('connections'),
    status: document.getElementById('status'),
    debug: document.getElementById('debug'),
    slider: document.getElementById('timeline'),
    timelineWrap: document.getElementById('timelineWrap'),
    timeLabel: document.getElementById('timeLabel'),
    manageFoldersBtn: document.getElementById('manageFoldersBtn'),
    settingsModal: document.getElementById('settingsModal'),
    rootsList: document.getElementById('rootsList'),
    addFolderBtn: document.getElementById('addFolderBtn'),
    saveSettingsBtn: document.getElementById('saveSettingsBtn'),
    closeSettingsBtn: document.getElementById('closeSettingsBtn'),
    includeVideosCheckbox: document.getElementById('includeVideosCheckbox'),
    refreshLibraryBtn: document.getElementById('refreshLibraryBtn'),
    searchInput: document.getElementById('searchInput'),
    clearSearchBtn: document.getElementById('clearSearchBtn'),
    filterPortraitBtn: document.getElementById('filterPortraitBtn'),
    filterGroupBtn: document.getElementById('filterGroupBtn'),
    floatingRecenterBtn: document.getElementById('floatingRecenterBtn'),
    clearCacheActionBtn: document.getElementById('clearCacheActionBtn'),
    groupBySelect: document.getElementById('groupByDropdown'),
    mapPanel: document.getElementById('map-panel'),
    mapModeWrap: document.getElementById('mapModeWrap'),
    mapModeMeta: document.getElementById('mapModeMeta'),
    fitMapBtn: document.getElementById('fitMapBtn'),
    mapStyleSelect: document.getElementById('mapStyleDropdown'),
    peopleModeWrap: document.getElementById('peopleModeWrap'),
    peopleCount: document.getElementById('peopleCount'),
    peopleUnnamed: document.getElementById('peopleUnnamed'),
    peopleSortSelect: document.getElementById('peopleSortDropdown'),
    navTimeline: document.getElementById('navTimeline'),
    navPeople: document.getElementById('navPeople'),
    navFamilyTree: document.getElementById('navFamilyTree'),
    navMap: document.getElementById('navMap'),
    renameModal: document.getElementById('renameModal'),
    renameInput: document.getElementById('renameInput'),
    closeRenameBtn: document.getElementById('closeRenameBtn'),
    saveRenameBtn: document.getElementById('saveRenameBtn'),
    loadingScreen: document.getElementById('loadingScreen'),
    loadingSubtitle: document.getElementById('loadingSubtitle'),
    loadingPhases: document.getElementById('loadingPhases'),
    loadingProgressWrap: document.getElementById('loadingProgressWrap'),
    loadingProgressBar: document.getElementById('loadingProgressBar'),
    loadingDetail: document.getElementById('loadingDetail'),
    relationshipModal: document.getElementById('relationshipModal'),
    relTypeDropdown: document.getElementById('relTypeDropdown'),
    relSaveBtn: document.getElementById('saveRelBtn'),
    relCancelBtn: document.getElementById('cancelRelBtn'),
    relCloseBtn: document.getElementById('closeRelModalBtn'),
    relPersonA: document.getElementById('relPersonA'),
    relPersonB: document.getElementById('relPersonB'),
    treeModeWrap: document.getElementById('treeModeWrap'),
    treePeopleCount: document.getElementById('treePeopleCount'),
    treeRelCount: document.getElementById('treeRelCount'),
    treeResetBtn: document.getElementById('treeResetBtn'),
    indexingHint: document.getElementById('indexingHint'),
    loadingSkipBtn: document.getElementById('loadingSkipBtn'),
};

const critical = ['viewport', 'gallery', 'connections', 'status'];
const missing = critical.filter(k => !ui[k]);
if (missing.length > 0) {
    console.error('MISSING CRITICAL UI ELEMENTS:', missing);
}
